-- Schema creation
CREATE TABLE IF NOT EXISTS Users (
    u_userid BIGINT PRIMARY KEY,
    u_totalScore INTEGER,
    u_username VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS TriviaSession (
    t_sessionid BIGINT PRIMARY KEY,
    t_startTime TIMESTAMP,
    t_stopTime TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Plays (
    p_userid BIGINT,
    p_sessionId BIGINT,
    p_score INTEGER,
    PRIMARY KEY (p_userid, p_sessionId),
    FOREIGN KEY (p_userid) REFERENCES Users(u_userid) ON DELETE CASCADE,
    FOREIGN KEY (p_sessionId) REFERENCES TriviaSession(t_sessionid) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Questions (
    q_questionid INTEGER PRIMARY KEY,
    q_hint VARCHAR(255),
    q_category VARCHAR(255),
    q_questionText VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Answers (
    a_answerid CHAR(1),
    a_questionid INTEGER,
    a_answertext VARCHAR(255) NOT NULL,
    a_isCorrect BOOLEAN,
    PRIMARY KEY (a_answerid, a_questionid),
    FOREIGN KEY (a_questionid) REFERENCES Questions(q_questionid) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Asked (
    as_sessionid BIGINT,
    as_questionid INTEGER,
    as_answeredby BIGINT,
    as_answer CHAR(1),
    as_iscorrect BOOLEAN,
    PRIMARY KEY (as_sessionid, as_questionid, as_answeredby),
    FOREIGN KEY (as_sessionid) REFERENCES TriviaSession(t_sessionid),
    FOREIGN KEY (as_questionid) REFERENCES Questions(q_questionid),
    FOREIGN KEY (as_answeredby) REFERENCES Users(u_userid)
);

-- Insert questions into the Questions table
INSERT INTO Questions (q_questionid, q_hint, q_category, q_questiontext) VALUES
(1, NULL, 'History', 'Which era marked a switch from agricultural practices to industrial practices?'),
(2, NULL, 'Geography', 'What United States city is known as "The City of Fountains?"'),
(3, NULL, 'Nature', 'What is the deadliest creature in the world?'),
(4, NULL, 'Entertainment', 'What do Katniss and Peeta attempt to poison themselves with in The Hunger Games?'),
(11, NULL, 'Nature', 'How many hearts does an octopus have?'),
(12, NULL, 'Nature', 'What is the only animal that cannot jump?'),
(13, NULL, 'Nature', 'How much does a blue whale tongue weigh?'),
(14, NULL, 'Nature', 'What bird has the longest migration?'),
(15, NULL, 'Nature', 'What color is polar bear skin?'),
(16, NULL, 'History', 'What country has the world''s oldest parliament?'),
(17, NULL, 'History', 'What was the length of the shortest war in history?'),
(18, NULL, 'History', 'How many giant head statues are on Easter Island?'),
(19, NULL, 'History', 'How many people died of bubonic plague during the Middle Ages?'),
(20, NULL, 'History', 'What year was the Great Wall of China completed?'),
(21, NULL, 'Geography', 'What continent can be found in all four hemispheres?'),
(22, NULL, 'Geography', 'What mountain is closest to space?'),
(23, NULL, 'Geography', 'What continent has the largest desert?'),
(24, NULL, 'Geography', 'What is the lowest natural point on Earth?'),
(25, NULL, 'Geography', 'What country has the most islands?'),
(26, NULL, 'Geography', 'How much closer does Hawaii get to Alaska every year?'),
(27, NULL, 'Sports', 'With 8000+ sports played around the world, how many are included in the Olympics?'),
(28, NULL, 'Sports', 'How many assists does Wayne Gretzky have?'),
(29, NULL, 'Sports', 'Who is the silhouette on the official NBA logo?'),
(30, NULL, 'Sports', 'What did Babe Ruth wear under his cap for good luck?'),
(31, NULL, 'Sports', 'What country has the largest bowling alley?'),
(32, NULL, 'Entertainment', 'What year was the first moving picture?'),
(33, NULL, 'Entertainment', 'What is Chuck Norris''s first name?'),
(34, NULL, 'Entertainment', 'Who is Mickey Mouse''s sister?'),
(35, NULL, 'Entertainment', 'What is the most popular ballet in the world?'),
(36, NULL, 'Entertainment', 'How often is a new porn film made in the US?'),
(37, NULL, 'Geography', 'What percentage of the population lives in the northern hemisphere?'),
(38, NULL, 'Geography', 'What is the only sea with no coast?'),
(39, NULL, 'Geography', 'How much taller do the Himalayas get every year?'),
(40, NULL, 'Geography', 'What country is the most linguistically diverse in the world?'),
(41, NULL, 'Sports', 'How many stitches are on a baseball?'),
(42, NULL, 'Sports', 'What is the length of the longest successful shot in NBA history?'),
(43, NULL, 'Sports', 'What sport popularized identifying players by their jersey number?'),
(44, NULL, 'Sports', 'What was the first sport played on the moon?'),
(45, NULL, 'Sports', 'What was used as the first ever puck in a hockey game?'),
(46, NULL, 'Entertainment', 'What movie has a Starbucks cup in every scene?'),
(47, NULL, 'Entertainment', 'How many commercials does the average child see each year?'),
(48, NULL, 'Entertainment', 'What was the first music video to air on MTV by a black artist?'),
(49, NULL, 'Entertainment', 'What was Hitler''s favorite movie?'),
(50, NULL, 'Entertainment', 'What is Tom Cruise''s real name?'),
(51, NULL, 'History', 'Prior to Covid19, what was the shortest record for a vaccine to be developed and licensed?'),
(52, NULL, 'History', 'Napoleon took 187,600 horses with his army as he rode into Russia in 1812, how many came back?'),
(53, NULL, 'History', 'When was the first skyscraper built?'),
(54, NULL, 'History', 'What percentage of English brides in 1800 were pregnant at the altar?'),
(55, NULL, 'History', 'When was the first powered flight by the Wright Brothers?'),
(56, NULL, 'Nature', 'How long can a scorpion hold its breath?'),
(57, NULL, 'Nature', 'What percentage of a cat''s bones are located in its tail?'),
(58, NULL, 'Nature', 'How many brains does an octopus have?'),
(59, NULL, 'Nature', 'What color is hippopotamus milk?'),
(60, NULL, 'Nature', 'What animal has the largest eyes in the world?');

-- Insert answers into the Answers table
INSERT INTO Answers (a_answerid, a_questionid, a_answertext, a_isCorrect) VALUES
('a', 1, 'Middle Ages', FALSE),
('b', 1, 'The Industrial Revolution', TRUE),
('c', 1, 'The Bronze Age', FALSE),
('a', 2, 'Phoenix', FALSE),
('b', 2, 'Salt Lake City', FALSE),
('c', 2, 'Kansas City', TRUE),
('a', 3, 'Mosquitoes', TRUE),
('b', 3, 'Killer Sharks', FALSE),
('c', 3, 'Humans', FALSE),
('a', 4, 'DeathBerries', FALSE),
('b', 4, 'Nightlock', TRUE),
('c', 4, 'Apples', FALSE),
('a', 11, '2', FALSE),
('b', 11, '3', TRUE),
('c', 11, '4', FALSE),
('a', 12, 'Elephant', TRUE),
('b', 12, 'Hippopotamus', FALSE),
('c', 12, 'Tortoise', FALSE),
('a', 13, '2,000lbs', FALSE),
('b', 13, '10,000lbs', FALSE),
('c', 13, '6,000lbs', TRUE),
('a', 14, 'Mottled Duck', FALSE),
('b', 14, 'American Woodcock', FALSE),
('c', 14, 'Arctic Tern', TRUE),
('a', 15, 'pink', FALSE),
('b', 15, 'black', TRUE),
('c', 15, 'white', FALSE),
('a', 16, 'China', FALSE),
('b', 16, 'Iceland', TRUE),
('c', 16, 'England', FALSE),
('a', 17, '38 minutes', TRUE),
('b', 17, '23 minutes', FALSE),
('c', 17, '52 minutes', FALSE),
('a', 18, '776', FALSE),
('b', 18, '887', TRUE),
('c', 18, '693', FALSE),
('a', 19, '60 million', FALSE),
('b', 19, '90 million', FALSE),
('c', 19, '75 million', TRUE),
('a', 20, '207 BC', FALSE),
('b', 20, '220 AD', FALSE),
('c', 20, '1878', TRUE),
('a', 21, 'Asia', FALSE),
('b', 21, 'South America', FALSE),
('c', 21, 'Africa', TRUE),
('a', 22, 'Chimborazo', TRUE),
('b', 22, 'Everest', FALSE),
('c', 22, 'K2', FALSE),
('a', 23, 'North America', FALSE),
('b', 23, 'Antarctica', TRUE),
('c', 23, 'Africa', FALSE),
('a', 24, 'Dead Sea', TRUE),
('b', 24, 'Death Valley', FALSE),
('c', 24, 'Purgatory', FALSE),
('a', 25, 'Indonesia', FALSE),
('b', 25, 'Philippines', FALSE),
('c', 25, 'Sweden', TRUE),
('a', 26, '12.1cm', FALSE),
('b', 26, '7.5cm', TRUE),
('c', 26, '10.2cm', FALSE),
('a', 27, '56', FALSE),
('b', 27, '82', FALSE),
('c', 27, '33', TRUE),
('a', 28, '1875', FALSE),
('b', 28, '1963', TRUE),
('c', 28, '1632', FALSE),
('a', 29, 'Jerry West', TRUE),
('b', 29, 'Wilt Chamberlain', FALSE),
('c', 29, 'Michael Jordan', FALSE),
('a', 30, 'playing card', FALSE),
('b', 30, 'cabbage leaf', TRUE),
('c', 30, 'family portrait', FALSE),
('a', 31, 'Ireland', FALSE),
('b', 31, 'United States', FALSE),
('c', 31, 'Japan', TRUE),
('a', 32, '1902', FALSE),
('b', 32, '1796', FALSE),
('c', 32, '1888', TRUE),
('a', 33, 'Carlos', TRUE),
('b', 33, 'Charles', FALSE),
('c', 33, 'William', FALSE),
('a', 34, 'Abigail Housemouse', FALSE),
('b', 34, 'Anna Pocketmouse', FALSE),
('c', 34, 'Amelia Fieldmouse', TRUE),
('a', 35, 'The Nutcracker', TRUE),
('b', 35, 'Swan Lake', FALSE),
('c', 35, 'Romeo and Juliet', FALSE),
('a', 36, '3 hours', FALSE),
('b', 36, '39 minutes', TRUE),
('c', 36, '53 seconds', FALSE),
('a', 37, '30', FALSE),
('b', 37, '50', FALSE),
('c', 37, '90', TRUE),
('a', 38, 'Sargasso Sea', TRUE),
('b', 38, 'Black Sea', FALSE),
('c', 38, 'Arabian Sea', FALSE),
('a', 39, '5mm', TRUE),
('b', 39, '1mm', FALSE),
('c', 39, '3mm', FALSE),
('a', 40, 'United States', FALSE),
('b', 40, 'China', FALSE),
('c', 40, 'Papua New Guinea', TRUE),
('a', 41, '112', FALSE),
('b', 41, '76', FALSE),
('c', 41, '108', TRUE),
('a', 42, '93ft', FALSE),
('b', 42, '89ft', TRUE),
('c', 42, '78ft', FALSE),
('a', 43, 'Basketball', FALSE),
('b', 43, 'Soccer', FALSE),
('c', 43, 'Baseball', TRUE),
('a', 44, 'Golf', TRUE),
('b', 44, 'Soccer', FALSE),
('c', 44, 'Darts', FALSE),
('a', 45, 'Crushed can', FALSE),
('b', 45, 'Frozen cow poop', TRUE),
('c', 45, 'Sliced fruit', FALSE),
('a', 46, 'Deadpool', FALSE),
('b', 46, 'Fight Club', TRUE),
('c', 46, 'The Social Network', FALSE),
('a', 47, '30,000', TRUE),
('b', 47, '10,000', FALSE),
('c', 47, '50,000', FALSE),
('a', 48, 'Sexual Healing', FALSE),
('b', 48, 'Cold Blooded', FALSE),
('c', 48, 'Billie Jean', TRUE),
('a', 49, 'Rudolph', FALSE),
('b', 49, 'King Kong', TRUE),
('c', 49, 'Viking', FALSE),
('a', 50, 'Thomas Pennyfeather', FALSE),
('b', 50, 'Thomas Mapother', TRUE),
('c', 50, 'Thomas Wormwell', FALSE),
('a', 51, '2 years', FALSE),
('b', 51, '4 years', TRUE),
('c', 51, '6 years', FALSE),
('a', 52, '1600', TRUE),
('b', 52, '106,000', FALSE),
('c', 52, '57,000', FALSE),
('a', 53, '1812', FALSE),
('b', 53, '1884', FALSE),
('c', 53, '1797', TRUE),
('a', 54, '40', TRUE),
('b', 54, '0', FALSE),
('c', 54, '70', FALSE),
('a', 55, '1910', FALSE),
('b', 55, '1903', TRUE),
('c', 55, '1912', FALSE),
('a', 56, '1 week', TRUE),
('b', 56, '1 day', FALSE),
('c', 56, '1 hour', FALSE),
('a', 57, '15', FALSE),
('b', 57, '5', FALSE),
('c', 57, '10', TRUE),
('a', 58, '2', FALSE),
('b', 58, '4', FALSE),
('c', 58, '9', TRUE),
('a', 59, 'White', FALSE),
('b', 59, 'Pink', TRUE),
('c', 59, 'Yellow', FALSE),
('a', 60, 'Giant squid', TRUE),
('b', 60, 'Blue whale', FALSE),
('c', 60, 'African elephant', FALSE);
